### ISSUE TITLE
errors, can't start

### ISSUE THREAD

**Issue by Maelstrom2014** [caleboleary/ComfyUI-Arc2Face#3]
your requirements.txt  conflicts with comfyui (balanced and work with all my 150+ custom nodes)
( req: transformers==4.34.1 crashes many other custom nodes.)

Traceback (most recent call last):
  File "C:\ai\comfyui\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI-Arc2Face\__init__.py", line 1, in <module>
    from .arc2face_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI-Arc2Face\arc2face_nodes.py", line 15, in <module>
    from .models import CLIPTextModelWrapper
  File "C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI-Arc2Face\models.py", line 5, in <module>
    from transformers.models.clip.modeling_clip import _make_causal_mask, _expand_mask
ImportError: cannot import name '_make_causal_mask' from 'transformers.models.clip.modeling_clip' (C:\ai\comfyui\python_embeded\Lib\site-packages\transformers\models\clip\modeling_clip.py)

Cannot import C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI-Arc2Face module for custom nodes: cannot import name '_make_causal_mask' from 'transformers.models.clip.modeling_clip' (C:\ai\comfyui\python_embeded\Lib\site-packages\transformers\models\clip\modeling_clip.py)

**Comment by caleboleary** [comment]
Thanks for the heads up. I've updated the tformers version in requirements and fixed the couple places the Arc2Face team were using some private functions no longer exposed. Seems to work ok for me now, lmk if that isn't the case for you

**Comment by Maelstrom2014** [comment]
Big THANX! Very quick fix! thanx a lot!

Is is possible to add a mask for input img2img mode?

**Comment by caleboleary** [comment]
I think it is possible, yes. If I have time I might or feel free to give it a go if you want and open a PR 👍
